### ISSUE TITLE
[Feature request] Ammo bars

### ISSUE THREAD

**Issue by SinaelDOverom** [jekyllgrim/UniversalFlexibleHUD#19]
Optional ammo bars, optionally with ammo counters and separate color and/or color  gradients that makes the bar change color as the ammo depletes?

Here's a mockup
![image](https://github.com/jekyllgrim/UniversalFlexibleHUD/assets/61930430/d1485738-4a93-40ea-92cf-2aaa4a5acb32)

Maybe be able to make it vertical as well, like in Unreal

**Comment by jekyllgrim** [comment]
You mean for All Ammo block, or for current ammo?

**Comment by SinaelDOverom** [comment]
An alternative/option for All Ammo block.

**Comment by jekyllgrim** [comment]
I've been thinking of adding this myself, however, one thing I cannot implement very efficiently is different colors for different ammo. Since the total number of ammo types is completely arbitrary and they get loaded dynamically from the current game, and it's not possible to dynamically construct a menu based on the existing ammo types, I don't see how this could be easily solved. I could, of course, just randomize colors, but thatt wouldn't look very nice. I can do this with a single color/gradient for all ammo types, though. Otherwise I'm willing to listen to suggestions.

**Comment by SinaelDOverom** [comment]
Single gradient would be ok too

**Comment by jekyllgrim** [comment]
Added in b1e3383a6d392a7994077e61cef93109a81ebcdc

The All Ammo block features a new option to display ammo bars. The bars are feature an orange-purple-blue gradient. It's recommended to switch Display type to "current amount only" with this mode, since it looks cleaner.
![Screenshot_27](https://github.com/jekyllgrim/UniversalFlexibleHUD/assets/42670463/59258ed0-a1de-458f-8781-230931ab86e2)
